//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHomeSimulator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AdditionalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdditionalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartHomeSimulator.AdditionalResources", typeof(AdditionalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bulbStrip {
            get {
                object obj = ResourceManager.GetObject("bulbStrip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Building StreetAddress=&quot;36 Symonds Street&quot;&gt;
        ///	&lt;Floor Name=&quot;Ground Floor&quot;&gt;
        ///		&lt;Room Name=&quot;Garage&quot;&gt;
        ///			&lt;Device Id=&quot;1&quot; Type=&quot;Bulb&quot;&gt;
        ///				&lt;Association Id=&quot;2&quot; /&gt;
        ///				&lt;Association Id=&quot;3&quot; /&gt;
        ///			&lt;/Device&gt;
        ///			&lt;Device Id=&quot;2&quot; Type=&quot;Bulb&quot; /&gt;
        ///		&lt;/Room&gt;
        ///		&lt;Room Name=&quot;Lobby&quot;&gt;
        ///			&lt;Device Id=&quot;3&quot; Type=&quot;Bulb&quot; /&gt;
        ///			&lt;Device Id=&quot;4&quot; Type=&quot;Window&quot; /&gt;
        ///		&lt;/Room&gt;
        ///	&lt;/Floor&gt;	
        ///	&lt;Floor Name=&quot;1st Floor&quot;&gt;
        ///		&lt;Room Name=&quot;Dining Room&quot;&gt;
        ///			&lt;Device Id=&quot;15&quot; Type=&quot;Bulb&quot;/&gt;
        ///			&lt;Device Id=&quot;14&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string layout {
            get {
                return ResourceManager.GetString("layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mediaStrip {
            get {
                object obj = ResourceManager.GetObject("mediaStrip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap upDownStrip {
            get {
                object obj = ResourceManager.GetObject("upDownStrip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap windowStrip {
            get {
                object obj = ResourceManager.GetObject("windowStrip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
